---
- name: install pip and docker on ubuntu
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-pip
    - docker
    - docker.io
  when: ansible_distribution == 'Ubuntu'

- name: install docker-py
  pip:
    name: docker-py
    version: 1.1.0
