---
- name: Pull (or update) Locust Image and Clean Existing Container 
  docker:
    image: ljishen/locust
    name: "{{ container_name }}"
    state: absent
    pull: always

- name: Ensure Locust Test Result Directory Exists
  file: path={{ ga4gh_working_dir }}/{{ test_results_folder_name }}/{{ locust_folder_name }} state=directory

- name: Run Load Testing
  shell: >
    docker run \
      -v {{ ga4gh_working_dir }}:/root  \
      --name {{ container_name }} \
      ljishen/locust  \
      /usr/local/bin/locust \
        -f /root/{{ locust_folder_name }}/{{ locust_filename }} \
        --host=http://{{ groups['server'][0] }}/ga4gh \
        --no-web --only-summary \
        --logfile {{ test_results_folder_name }}/{{ locust_folder_name }}/{{ locust_log_filename }} \
        -c {{ num_clients }} \
        -r {{ hatch_rate }} \
        -n {{ num_requests }} \
            >{{ ga4gh_working_dir }}/{{ test_results_folder_name }}/{{ locust_folder_name }}/{{ locust_stats_filename }} \
            2>&1
  ignore_errors: yes
