---
- name: Pull (or update) Locust Image and Clean Existing Container 
  docker:
    image: ljishen/locust
    name: "{{ locust_container_name }}"
    state: absent
    pull: always

- name: Ensure Locust Test Results Directory Exists
  file: path={{ locust_test_results_path }} state=directory

- name: Run Load Testing
  shell: >
    docker run \
      -v {{ ga4gh_working_dir }}/{{ locust_folder_name }}/{{ locust_filename }}:/root/{{ locust_filename }}:ro \
      -v {{ locust_test_results_path }}:/root/{{ test_results_folder_name }} \
      --name {{ locust_container_name }} \
      ljishen/locust  \
        -f /root/{{ locust_filename }} \
        --host=http://{{ groups['server'][0] }}/ga4gh \
        --no-web --only-summary \
        --logfile {{ test_results_folder_name }}/{{ locust_log_filename }} \
        -c {{ num_clients }} \
        -r {{ hatch_rate }} \
        -n {{ num_requests }} \
            > {{ locust_test_results_path }}/{{ locust_stats_filename }} \
            2>&1
  ignore_errors: True
