- name: Install Docker on Server
  any_errors_fatal: true
  hosts: all
  become: yes
  roles:
    - { role: angstwad.docker_ubuntu, when: install_docker }

- name: Deploy GA4GH Reference Server
  hosts: server
  become: yes
  gather_facts: no
  roles:
    - { role: server, when: deploy_server }

- name: Run Locust
  hosts: locust
  become: yes
  gather_facts: no
  vars:
    num_hosts: "{{ groups['locust'] | length }}"
    container_name: "locust"
  pre_tasks:
    - name: Download locustfile
      get_url: url={{ locustfile_url }} dest={{ volume_host_dir }}/{{ locust_filename }} force=yes
      when: locustfile_url is defined
  roles:
    - { role: locust/standalone, when: num_hosts | int == 1 }
    - { role: locust/distributed, when: num_hosts | int != 1 }
