- name: Install Docker on Server
  any_errors_fatal: true
  hosts: all
  become: yes
  roles:
    - { role: angstwad.docker_ubuntu, when: install_docker }

- name: Deploy GA4GH Reference Server
  hosts: server
  become: yes
  gather_facts: no
  roles:
    - { role: server, when: deploy_server }

- name: Deloy Locust
  hosts: locust
  gather_facts: no
  become: yes
  roles:
    - locust
