- name: install docker 
  hosts: all
  become: yes
  roles:
    - { role: common, when: install_docker }

- name: deploy ga4gh reference server
  hosts: server
  gather_facts: no
  roles:
    - { role: server, when: deploy_server }

- name: deloy locust
  hosts: locust
  gather_facts: no
  roles:
    - locust
