- name: Install Docker on Server
  any_errors_fatal: true
  hosts: all
  become: yes
  roles:
    - { role: angstwad.docker_ubuntu, when: install_docker }


- name: Deploy GA4GH Reference Server
  hosts: server
  become: yes
  gather_facts: no

  vars:
    server_volume_host_dir: "{{ volume_host_dir }}/srv/data"
    server_image_name: "macieksmuga/ga4gh-server-m2:docker2"
    registry_db_filename: registry.db

  pre_tasks:
    - stat: path={{ server_volume_host_dir }}/{{ registry_db_filename }}
      register: registry_db

  roles:
    - { role: create_registry, when: deploy_server and (not registry_db.stat.exists) }
    - { role: server, when: deploy_server }

- name: Run Compliance Test Suite
  hosts: master
  become: yes
  gather_facts: no
  roles:
    - { role: compliance_tests }

- name: Run Locust
  hosts: locust
  become: yes
  gather_facts: no

  vars:
    num_slaves: "{{ groups.slave | length }}"
    container_name: "locust"

  pre_tasks:
    - name: Download locustfile
      get_url: url={{ locustfile_url }} dest={{ locust_volume_host_dir }}/{{ locust_filename }} force=yes
      when: locustfile_url is defined

  roles:
    - { role: locust_standalone, when: num_slaves | int == 0 }
    - { role: locust_distributed, when: num_slaves | int != 0 }


# TODO:
#   - Get compliance source code commit hash (Use template?)
#   - Move compliance testresults to HTTP Server folder

- name: Get Stats File Suffix
  hosts: server
  become: yes
  gather_facts: no
  roles:
    - { role: query_commit_hash, when: groups.slave | length == 0 }

- name: Move Locust Stats File to HTTP Server
  hosts: master
  gather_facts: no
  tasks:
    - name: Fetch Stats File from Master
      fetch:
        fail_on_missing: yes
        flat: yes
        src: "{{ locust_volume_host_dir }}/{{ locust_stats_filename }}"
        dest: "{{ file_server_dir }}/locust_stats_file_{{ hostvars[groups['server'][0]]['commit_hash']['stdout'] }}.log"
      when: groups.slave | length == 0
