- name: Download GA4GH Data
  unarchive:
    src: "{{ data_source_url }}"
    dest: "{{ data_source_path }}"
    copy: no
    creates: "{{ data_source_path }}/{{ data_source_folder }}"

# Temporary disable this resource until server docker image updated
#- name: download NCBI37 Reference set
#  unarchive:
#    src: "{{ ncbi37_ref_set_url }}"
#    dest: "{{ data_source_path }}/{{ data_source_folder }}"
#    copy: no
#    creates: "{{ data_source_path }}/{{ data_source_folder }}/referenceSets/NCBI37"

- name: Download Sequence Annotations DB
  get_url:
    url: "{{ sequence_annotations_db_url }}"
    dest: "{{ data_source_path }}/{{ data_source_folder }}/gencode_v24lift37.db"
    force: no

- name: Start GA4GH Reference Server
  docker:
    image: ljishen/ga4gh-server
    name: "{{ server_container_name }}"
    state: reloaded
    pull: always
    restart_policy: on-failure
    volumes: "{{ data_source_path }}/{{ data_source_folder }}:/srv/ga4gh/data:ro"
    ports: 80:80
    env:
      GA4GH_DEBUG: True
      GA4GH_DATA_SOURCE: /srv/ga4gh/data/repo.db
