---
- name: Start GA4GH Reference Server
  docker:
    image: "{{ server_image_name }}"
    name: "{{ server_container_name }}"
    state: reloaded
    pull: always
    restart_policy: on-failure
    volumes: "{{ server_volume_host_dir }}/{{ data_source_folder }}:/data:ro"
    ports: 80:80
    env:
      GA4GH_DEBUG: True
      GA4GH_DATA_SOURCE: /data/{{ registry_db_filename }}
