---
- name: Download locustfile.py
  get_url: url={{ locustfile_url }} dest={{ locustfile_path }}
  when: locustfile_url is defined

- name: Count Locust Hosts
  set_fact: num_hosts="{{ groups.locust | length }}"

- name: Show Number of Locust Hosts
  debug: msg="Number of Locust hosts is {{ num_hosts }}"

- name: Check if Master
  set_fact: comm_args="--master"
  when: (num_hosts != "1") and (groups.locust.index(inventory_hostname) == 0)

- name: Check if Slave
  set_fact: comm_args="--slave --master-host={{ groups.server[0] }}"
  when: (num_hosts != "1") and (not groups.locust.index(inventory_hostname) == 0)

- name: Start Locust
  docker:
    image: ljishen/locust
    name: locust
    state: reloaded
    pull: always
    ports:
      - "8089:8089"
      - "5557:5557"
    volumes: /tmp/locustfile.py:/root/locustfile.py:ro
    command: /usr/local/bin/locust --host=http://{{ groups['server'][0] }} {{ comm_args | default("")}}
